import {deployments} from "./deployments";

export type Chain = {
  name: ChainName,
  chainId: number | string,
  status: ChainStatus,
  img: string,
  multisig?: `0x${string}`,
  chainLibGithubId?: number,
}

export const enum ChainStatus {
  SUPPORTED = 'SUPPORTED',
  AWAITING_DEPLOYMENT = 'AWAITING_DEPLOYMENT',
  CHAINLIB_DEVELOPMENT = 'CHAINLIB_DEVELOPMENT',
  AWAITING_DEVELOPER = 'AWAITING_DEVELOPER',
  AWAITING_ISSUE_CREATION = 'AWAITING_ISSUE_CREATION',
  NOT_SUPPORTED = 'NOT_SUPPORTED',
}

export const enum ChainName {
  ETHEREUM = 'Ethereum',
  ARBITRUM = 'Arbitrum One',
  BASE = 'Base',
  POLYGON = 'Polygon',
  AVALANCHE = 'Avalanche C-Chain',
  BSC = 'Binance Smart Chain',
  CELO = 'Celo',
  FANTOM = 'Fantom',
  LINEA = 'Linea',
  GNOSIS = 'Gnosis',
  METIS = 'Metis Andromeda',
  MOONBEAM = 'Moonbeam',
  MOONRIVER = 'Moonriver',
  OPTIMISM = 'Optimism',
  POLYGON_ZKEVM = 'Polygon zkEVM',
  IMMUTABLE_ZKEVM = 'Immutable zkEVM',
  ASTAR_ZKEVM = 'Astar zkEVM',
  ZKFAIR = 'ZKFair',
  SCROLL = 'Scroll',
  ZKSYNC = 'zkSync',
  BLAST = 'Blast',
  MANTA = 'Manta Pacific',
  MANTLE = 'Mantle',
  MODE = 'Mode',
  BOBA = 'Boba',
  KLAYTN = 'Klaytn Cypress',
  AURORA = 'Aurora',
  DOGECHAIN = 'Dogechain',
  X_LAYER = 'X Layer',
  KAVA = 'Kava',
  FRAXTAL = 'Fraxtal',
  ROLLUX = 'Rollux',
  EVMOS = 'Evmos',
  TELOS = 'Telos EVM',
  ZETA = 'ZetaChain',
  MERLIN = 'Merlin',
  SKALE_EUROPA = 'SKALE Europa',
  SEI = 'Sei',
  ARBITRUM_NOVA = 'Arbitrum Nova',
  BITTORRENT = 'BitTorrent Chain',
  CORE = 'Core',
  FILECOIN = 'Filecoin',
  FUSE = 'Fuse',
  HAQQ = 'Haqq',
  ROOTSTOCK = 'Rootstock',
  THUNDERCORE = 'ThunderCore',
  KROMA = 'Kroma',
  WEMIX = 'WEMIX3.0',
  REAL = 'Re.al',
  HEDERA = 'Hedera',
}

export const chains: { [chainId: string]: Chain } = {
  "1": {
    name: ChainName.ETHEREUM,
    chainId: 1,
    status: ChainStatus.AWAITING_DEPLOYMENT,
    img: 'ethereum.svg',
    multisig: '0xEb49018157bAF7F1B385657D10fF5a5a5F4BB4c9',
    chainLibGithubId: 153,
  },
  "10": {
    name: ChainName.OPTIMISM,
    chainId: 10,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'optimism.svg',
  },
  "30": {
    name: ChainName.ROOTSTOCK,
    chainId: 30,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'rootstock.png',
  },
  "40": {
    name: ChainName.TELOS,
    chainId: 40,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'telos.svg',
  },
  "56": {
    name: ChainName.BSC,
    chainId: 56,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'bsc.svg',
  },
  "100": {
    name: ChainName.GNOSIS,
    chainId: 100,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'gnosis.svg',
  },
  "108": {
    name: ChainName.THUNDERCORE,
    chainId: 108,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'thundercore.png',
  },
  "122": {
    name: ChainName.FUSE,
    chainId: 122,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'fuse.svg',
  },
  "137": {
    name: ChainName.POLYGON,
    chainId: 137,
    status: ChainStatus.SUPPORTED,
    img: 'polygon.svg',
    multisig: '0x36780E69D38c8b175761c6C5F8eD42E61ee490E9',
  },
  "169": {
    name: ChainName.MANTA,
    chainId: 169,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'manta.png',
  },
  "196": {
    name: ChainName.X_LAYER,
    chainId: 196,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'x-layer.webp',
  },
  "199": {
    name: ChainName.BITTORRENT,
    chainId: 199,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'bittorrent.png',
  },
  "250": {
    name: ChainName.FANTOM,
    chainId: 250,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'fantom.png',
  },
  "252": {
    name: ChainName.FRAXTAL,
    chainId: 252,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'fraxtal.webp',
  },
  "255": {
    name: ChainName.KROMA,
    chainId: 255,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'kroma.png',
  },
  "288": {
    name: ChainName.BOBA,
    chainId: 288,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'boba.svg',
  },
  "295": {
    name: ChainName.HEDERA,
    chainId: 295,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'hedera.svg',
  },
  "314": {
    name: ChainName.FILECOIN,
    chainId: 314,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'filecoin.png',
  },
  "324": {
    name: ChainName.ZKSYNC,
    chainId: 324,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'zksync.png',
  },
  "570": {
    name: ChainName.ROLLUX,
    chainId: 570,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'rollux.jpg',
  },
  "1088": {
    name: ChainName.METIS,
    chainId: 1088,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'metis.png',
  },
  "1101": {
    name: ChainName.POLYGON_ZKEVM,
    chainId: 1101,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'polygon-zkevm.png',
  },
  "1111" : {
    name: ChainName.WEMIX,
    chainId: 1111,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'wemix.svg',
  },
  "1116": {
    name: ChainName.CORE,
    chainId: 1116,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'core-blockchain.png',
  },
  "1284": {
    name: ChainName.MOONBEAM,
    chainId: 1284,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'moonbeam.png',
  },
  "1285": {
    name: ChainName.MOONRIVER,
    chainId: 1285,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'moonriver.webp',
  },
  "1329": {
    name: ChainName.SEI,
    chainId: 1329,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'sei.png',
  },
  "2000": {
    name: ChainName.DOGECHAIN,
    chainId: 2000,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'dogechain.png',
  },
  "2222": {
    name: ChainName.KAVA,
    chainId: 2222,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'kava.png',
  },
  "3776": {
    name: ChainName.ASTAR_ZKEVM,
    chainId: 3776,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'astar-zkevm.png',
  },
  "4200": {
    name: ChainName.MERLIN,
    chainId: 4200,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'merlin.webp',
  },
  "5000": {
    name: ChainName.MANTLE,
    chainId: 5000,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'mantle.svg',
  },
  "7000": {
    name: ChainName.ZETA,
    chainId: 7000,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'zetachain.png',
  },
  "8217": {
    name: ChainName.KLAYTN,
    chainId: 8217,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'klaytn.png',
  },
  "8453": {
    name: ChainName.BASE,
    chainId: 8453,
    status: ChainStatus.SUPPORTED,
    img: 'base.svg',
    multisig: '0x626Bd898ca994c11c9014377f4c50d30f2B0006c',
    chainLibGithubId: 143,
  },
  "9001": {
    name: ChainName.EVMOS,
    chainId: 9001,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'evmos.png',
  },
  "11235": {
    name: ChainName.HAQQ,
    chainId: 11235,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'haqq.png',
  },
  "13371": {
    name: ChainName.IMMUTABLE_ZKEVM,
    chainId: 13371,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'immutable-zkevm.png',
  },
  "34443": {
    name: ChainName.MODE,
    chainId: 34443,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'mode.png',
  },
  "42161": {
    name: ChainName.ARBITRUM,
    chainId: 42161,
    status: ChainStatus.AWAITING_DEPLOYMENT,
    img: 'arbitrum.svg',
    multisig: '0xE28e3Ee2bD10328bC8A7299B83A80d2E1ddD8708',
    chainLibGithubId: 142,
  },
  "42170": {
    name: ChainName.ARBITRUM_NOVA,
    chainId: 42170,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'arbitrum-nova.jpg',
  },
  "42220": {
    name: ChainName.CELO,
    chainId: 42220,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'celo.svg',
  },
  "42766": {
    name: ChainName.ZKFAIR,
    chainId: 42766,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'zkfair.png',
  },
  "43114": {
    name: ChainName.AVALANCHE,
    chainId: 43114,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'avalanche.png',
  },
  "59144": {
    name: ChainName.LINEA,
    chainId: 59144,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'linea.webp',
  },
  "81457": {
    name: ChainName.BLAST,
    chainId: 81457,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'blast.png',
  },
  "111188": {
    name: ChainName.REAL,
    chainId: 111188,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'real.webp',
  },
  "534352": {
    name: ChainName.SCROLL,
    chainId: 534352,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'scroll.webp',
  },
  "1313161554": {
    name: ChainName.AURORA,
    chainId: 1313161554,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'aurora.webp',
  },
  "2046399126": {
    name: ChainName.SKALE_EUROPA,
    chainId: 2046399126,
    status: ChainStatus.NOT_SUPPORTED,
    img: 'skale-europa.jpg',
  },
}

export const getSupportedChainNames = (): ChainName[] => Object.keys(deployments).map(chainId => chains[chainId].name)

export const getChainsTotals = (): {[status in ChainStatus]: number} => {
  const ids = Object.keys(chains)
  return {
    [ChainStatus.SUPPORTED]: ids.filter(networkId => chains[networkId].status == ChainStatus.SUPPORTED ).length,
    [ChainStatus.AWAITING_DEPLOYMENT]: ids.filter(networkId => chains[networkId].status == ChainStatus.AWAITING_DEPLOYMENT ).length,
    [ChainStatus.CHAINLIB_DEVELOPMENT]: ids.filter(networkId => chains[networkId].status == ChainStatus.CHAINLIB_DEVELOPMENT ).length,
    [ChainStatus.AWAITING_DEVELOPER]: ids.filter(networkId => chains[networkId].status == ChainStatus.AWAITING_DEVELOPER ).length,
    [ChainStatus.AWAITING_ISSUE_CREATION]: ids.filter(networkId => chains[networkId].status == ChainStatus.AWAITING_ISSUE_CREATION ).length,
    [ChainStatus.NOT_SUPPORTED]: ids.filter(networkId => chains[networkId].status == ChainStatus.NOT_SUPPORTED ).length,
  }
}
